# Generated by Django 4.0.6 on 2022-08-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaCuenta',
            fields=[
                ('movimiento_id', models.AutoField(primary_key=True, serialize=False)),
                ('old_id', models.IntegerField()),
                ('new_id', models.IntegerField()),
                ('old_balance', models.IntegerField()),
                ('new_balance', models.IntegerField()),
                ('old_iban', models.TextField()),
                ('new_iban', models.TextField()),
                ('old_type', models.IntegerField()),
                ('new_type', models.IntegerField()),
                ('user_action', models.TextField()),
                ('created_at', models.DateField()),
            ],
            options={
                'db_table': 'auditoria_cuenta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConjuntoDirecciones',
            fields=[
                ('conjunto_direcciones_id', models.AutoField(primary_key=True, serialize=False)),
                ('propietario_id', models.IntegerField()),
                ('direccion_id', models.IntegerField()),
            ],
            options={
                'db_table': 'conjunto_direcciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('iban', models.TextField()),
                ('tipo_id', models.IntegerField()),
            ],
            options={
                'db_table': 'cuenta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('direccion_id', models.AutoField(primary_key=True, serialize=False)),
                ('calle', models.TextField()),
                ('ciudad', models.TextField()),
                ('provincia', models.TextField()),
                ('pais', models.TextField()),
            ],
            options={
                'db_table': 'direccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.TextField()),
                ('employee_surname', models.TextField()),
                ('employee_hire_date', models.TextField()),
                ('employee_dni', models.TextField(db_column='employee_DNI')),
                ('branch_id', models.IntegerField()),
                ('propietario_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MarcaTarjetas',
            fields=[
                ('marca_id', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.TextField()),
            ],
            options={
                'db_table': 'marca_tarjetas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('movimiento_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_id', models.IntegerField()),
                ('monto', models.IntegerField()),
                ('tipo_id', models.IntegerField()),
                ('hora', models.DateTimeField()),
            ],
            options={
                'db_table': 'movimientos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_type', models.TextField()),
                ('loan_date', models.TextField()),
                ('loan_total', models.IntegerField()),
                ('customer_id', models.IntegerField()),
            ],
            options={
                'db_table': 'prestamo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_number', models.IntegerField()),
                ('branch_name', models.TextField()),
                ('branch_address_id', models.IntegerField()),
                ('direccion_id', models.IntegerField()),
            ],
            options={
                'db_table': 'sucursal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.TextField()),
                ('cvv', models.IntegerField(db_column='CVV')),
                ('fecha_otorgamiento', models.DateField()),
                ('fecha_expiracion', models.DateField()),
                ('tipo_id', models.IntegerField()),
                ('marca_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
            ],
            options={
                'db_table': 'tarjeta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('tipo_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.TextField()),
            ],
            options={
                'db_table': 'tipo_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCuenta',
            fields=[
                ('tipo_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.TextField()),
            ],
            options={
                'db_table': 'tipo_cuenta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoOperaciones',
            fields=[
                ('tipo_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_name', models.TextField()),
            ],
            options={
                'db_table': 'tipo_operaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoTarjeta',
            fields=[
                ('tipo_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_name', models.TextField()),
            ],
            options={
                'db_table': 'tipo_tarjeta',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
    ]
