# Generated by Django 4.0.6 on 2022-08-12 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0007_cliente_delete_cliente_temp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Cliente_temp',
        ),
    ]
