# Generated by Django 4.0.6 on 2022-08-12 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0008_rename_cliente_cliente_temp'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente_temp',
            table='cliente_temp',
        ),
    ]
