# Generated by Django 4.0.6 on 2022-08-12 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0011_cliente_temp_delete_cliente'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente_temp',
            new_name='Cliente',
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='cliente',
        ),
    ]
