# Generated by Django 4.0.6 on 2022-08-12 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0014_alter_cliente_options_alter_cuenta_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuenta',
            options={},
        ),
        migrations.AlterModelOptions(
            name='prestamo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tarjeta',
            options={},
        ),
    ]
