# Generated by Django 4.0.6 on 2022-08-12 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0016_alter_cuenta_customer_id_alter_prestamo_customer_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuenta',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='tarjeta',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
