# Generated by Django 4.0.6 on 2022-08-12 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0017_rename_customer_id_cuenta_customer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={},
        ),
    ]
