# Generated by Django 4.0.6 on 2022-08-12 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0021_rename_tipo_id_cuenta_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuenta',
            options={'managed': False},
        ),
    ]
