# Generated by Django 4.0.6 on 2022-08-12 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0025_alter_prestamo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestamo',
            options={'managed': False},
        ),
    ]
