# Generated by Django 4.0.6 on 2022-08-25 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={},
        ),
    ]
