# Generated by Django 4.0.6 on 2022-08-25 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0002_alter_cliente_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': False},
        ),
    ]
