# Generated by Django 4.0.6 on 2022-08-25 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0005_remove_cliente_tipo_id_cliente_tipo_cliente_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='direccion_id',
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='direccion', to='Common.direccion'),
            preserve_default=False,
        ),
    ]
