# Generated by Django 4.0.6 on 2022-08-25 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0006_remove_cliente_direccion_id_cliente_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='branch_id',
        ),
        migrations.AddField(
            model_name='cliente',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='Common.sucursal'),
            preserve_default=False,
        ),
    ]
