# Generated by Django 4.0.6 on 2022-08-25 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0008_alter_empleado_options_alter_sucursal_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='branch_id',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='direccion_id',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='direccion_id',
        ),
        migrations.AddField(
            model_name='empleado',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='branchEmpleado', to='Common.sucursal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='direccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='direccionEmpleado', to='Common.direccion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sucursal',
            name='direccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='direccionSucursal', to='Common.direccion'),
            preserve_default=False,
        ),
    ]
