# Generated by Django 4.0.6 on 2022-08-25 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0009_remove_empleado_branch_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarjeta',
            options={},
        ),
    ]
