# Generated by Django 4.0.6 on 2022-08-25 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0010_alter_tarjeta_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjeta',
            name='marca_id',
        ),
        migrations.RemoveField(
            model_name='tarjeta',
            name='tipo_id',
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clienteTarjeta', to='Common.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='marca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='marcaTarjeta', to='Common.marcatarjetas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tipoTarjeta', to='Common.tipotarjeta'),
            preserve_default=False,
        ),
    ]
