# Generated by Django 4.0.6 on 2022-08-25 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0011_remove_tarjeta_marca_id_remove_tarjeta_tipo_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestamo',
            options={},
        ),
    ]
