# Generated by Django 4.0.6 on 2022-08-25 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0012_alter_prestamo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientos',
            options={},
        ),
        migrations.AddField(
            model_name='prestamo',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientePrestamo', to='Common.cliente'),
        ),
    ]
