# Generated by Django 4.0.6 on 2022-08-26 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0014_alter_cuenta_options_remove_movimientos_tipo_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='cuenta',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='movimientos',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='prestamo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sucursal',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tarjeta',
            options={'managed': False},
        ),
    ]
